/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compiler;

import compiler.CodeGenerator.CodeGenerator;
import compiler.Lexer.Lexer;
import compiler.Parser.AST.ProgramNode;
import compiler.Parser.Parser;
import compiler.Semantic.SemanticAnalyzer;

import java.io.FileReader;
import java.io.IOException;


public class Compiler {
    public static void main(String[] args) throws IOException {

        if (args.length != 1) {
            System.err.println("Incorrect number of args ");
            System.exit(1);
        }
        String fileName = args[0];
        try (FileReader reader = new FileReader(fileName)) {
            Lexer lexer = new Lexer(reader);
            Parser parser = new Parser(lexer);
            ProgramNode ast = parser.getAST();
            System.out.println(ast);
            SemanticAnalyzer analyzer = new SemanticAnalyzer();
            analyzer.analyze(ast);
            System.out.println("analyse finie sans erreur");
            CodeGenerator generator = new CodeGenerator();
            generator.generate(ast, "Main.class");
            System.out.println("Class file generated.");
        } catch (IOException e) {
            System.err.println("Cannot read input file");
            System.exit(1);
        } catch (RuntimeException e) {
            System.err.println(e.getMessage());
            System.exit(1);
        } catch (Exception e) {
            System.err.println("Unexpected error: " + e.getMessage());
            System.exit(1);
        }

    }
}